version: "3.9"
services:
  api:
    build: .
    container_name: dragonroll-gameserver
    environment:
      DB_URI: postgresql://postgres:postgres@db/dragonroll_dev
    ports:
      - "8000:80"
    depends_on:
      - "db"
  db:
    container_name: postgres-test-server
    environment:
      POSTGRES_PASSWORD: postgres
    image: "postgres:14.5"
    ports:
      - "5432:5432"